set(_AMENT_PACKAGE_NAME "turtlebot3_gazebo")
set(turtlebot3_gazebo_VERSION "0.0.0")
set(turtlebot3_gazebo_MAINTAINER "biswash <077bme014.biswash@pcampus.edu.np>")
set(turtlebot3_gazebo_BUILD_DEPENDS )
set(turtlebot3_gazebo_BUILDTOOL_DEPENDS "ament_cmake")
set(turtlebot3_gazebo_BUILD_EXPORT_DEPENDS )
set(turtlebot3_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(turtlebot3_gazebo_EXEC_DEPENDS )
set(turtlebot3_gazebo_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(turtlebot3_gazebo_GROUP_DEPENDS )
set(turtlebot3_gazebo_MEMBER_OF_GROUPS )
set(turtlebot3_gazebo_DEPRECATED "")
set(turtlebot3_gazebo_EXPORT_TAGS)
list(APPEND turtlebot3_gazebo_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
